--- 
title: "GLODIUM"
subtitle: "Glossario di Informatica Umanistica"
author:
- Antonello Fabio Caterino
- Marcello Bolpagni
- Marco Petolicchio
- Alessandra Di Meglio
- Vincenzo Vozza
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: scrbook
classoption: [b5paper,twoside,12pt,chapterprefix=false, bibliography=totocnumbered, parskip=false]
link-citations: yes
github-repo: https://github.com/glo-d-i-um/glo-d-i-um.github.io/
description: "GLODIUM"
always_allow_html: yes
output:
    bookdown::pdf_book:
        - lot: no
        - lof: no
        - toc: no
---




# GLODIUM -- Glossario di Informatica Umanistica. Cui prodest? {-}

\markboth{GLODIUM -- Glossario di Informatica Umanistica. Cui prodest?}{Antonello Fabio Caterino}

## Le grandi quantità di dati fanno paura a molte discipline: informatica, economia, matematica, statistica, filosofia. Perché non dovrebbero terrorizzare anche noi umanisti? {-}

Ci avviciniamo con cautela a un futuro pieno di informazioni
immediatamente disponibili, lasciandoci sempre più alle spalle un
passato -- che idealizziamo, senza troppa memoria storica -- in cui i
dati a disposizione erano davvero pochi, chiusi per di più nel cassetto
di chi decideva di volta involta come usarli e se concederne
l'usufrutto.

Le paure si affrontano affrontando di volta in volta le situazioni che
generano in noi questo senso di perdizione: non certo evitandole;
qualsiasi esperto in psiche umana potrà comodamente dirci, in caso
contrario, che non c'è niente di peggio dai *loop* derivati dalla paura
della paura. Sembra proprio che la diffidenza verso l'informatica
umanistica sia uno di questi *loop*: temiamo i dati, la loro
sconvolgente capacità di confonderci, e dunque evitiamo di cimentarci
con essi, rinunciando così sin troppe volte alle sconvolgenti
opportunità di conoscere e migliorare che essi ci offrono. È facile
gestire poche informazioni (e coronarsi maestri d'esse), ma è davvero
una blasfemia ermeneutica rinunciare ad aumentare la conoscenza generale
di una disciplina per paura di non riuscire a gestirne numero maggiore.

Eppure non abbiamo bisogno dell'informatica umanistica solo per
orientarci nella selva dei *big data* che le nuove tecnologie --
*obtorto collo* -- ci offrono: ne abbiamo anche necessità per andare
oltre i difetti convenzionali dell'isolazionismo disciplinare. I vari
settori scientifico-disciplinari sono -- nella sezione del sapere che
convenzionalmente chiamiamo umanistica -- sin troppo isolati gli uni
dagli altri, forse perché è meno sentito tra gli umanisti il concetto di
squadra (che rivive -- ad esempio -- in un laboratorio scientifico).
Tramite l'informatica sarebbe, invece, possibile creare piattaforme
collaborative in cui ognuno è chiamato a svolgere una mansione,
nell'ottica della ricerca generale; ciascuno secondo le proprie
competenze e abilità di partenza, che mai e poi mai dovranno essere
snaturate da ingenui principi di "tuttologia".

Orientarsi tra i *big data*, gestire più informazioni
contemporaneamente, creare filtri sempre più precisi per i vari
risultati delle ricerche, offrire piattaforme e modelli di
collaborazione ai ricercatori: a fronte di tutti questi vantaggi, sembra
ancora assurdo che manipoli di intellettuali duri e puri continui a
tuonare contro la tecnologia applicata alla scienze umane; come se --
tra parentesi -- le scienze umane non fossero pioniere stesse del
concetto di tecnologia. L'informatica è del resto bastata sul concetto
stesso di grammatica, dunque quanto può essere impreciso -- per non dire
peggio -- un umanista che rifugge una disciplina pronipote di una
categoria logica di sua stessa competenza?!

Bisogna altresì spendere almeno un paio di parole sui profondi
miglioramenti che l'informatica umanistica potrebbe offrire al concetto
stesso di didattica. Le stesse piattaforme utili per i ricercatori con
qualche modifica potrebbero essere utili per mantenere costanti rapporti
tra studenti e docenti, per condividere sul momento materiali di studio,
per offrire l'interazione necessaria perché l'istruzione abbia i suoi
maggiori frutti, supponendo che il modello didattico più valido sia
ancora quello basato su domanda/risposta. Anche da questo punto di vista
si assiste, però, a una fiera dell'oscena cecità intellettuale, che
culminano di solito in qualche crociata per l'abolizione dell'uso degli
*smartphone* nelle scuole, come se prima del telefonino gli studenti non
sapessero procacciarsi altrettante distrazioni dal loro percorso.

Queste sono poche considerazioni introduttive, che intendono offrire --
a mo' di volo d'aquila -- una panoramica generale sui possibili vantaggi
di non chiudersi a riccio di fronte all'informatica umanistica. Non si
vuole entrare nel particolare, ad esempio nel confronto tra i commenti
ai testi editi in era pre-informatica coi commenti stilati con l'ausilio
di *corpora* elettronici: sarebbe addirittura imbarazzante continuare a
lodare la precisione dei nuovi strumenti. Certo, ci vogliono ricercatori
e studiosi capaci di usare le nuove tecnologie senza mai considerarle
una scorciatoia. I rovesci della medaglia esistono, del resto, da quando
noi umani ci siamo resi conto che nel conio il minor numero di facce è
due (pur supponendo che una delle due sia completamente vuota).

Linneo -- grande profeta della classificazione tassonomica -- si
espresse eccellentemente dicendo *nomina si nescis, perit et cognitio
rerum*. Ciò vale anche per l'informatica umanistica: non conoscere i
nomi dei concetti di cui si avvale equivale a fare una grandissima
confusione.

Per concludere davvero: se l'informatica umanistica può essere utile,
può essere ancor più utile avere a disposizione uno strumento di
orientamento interno che sappia definire ogni istanza al suo interno, in
modo da renderla un campo funzionante e funzionale a qualsiasi prospetto
di studio o ricerca in ambito umanistico. Speriamo che il GLODIUM possa
dare in tal senso una consistente mano.

GLODIUM nasce come strumento online[^1] e come tale è stato inserito
dall'EADH tra i progetti più significativi degli ultimi cinque anni[^2]
-- in europa -- nel campo delle *digital humanities*. L'intento della
versione cartacea è principalmente manualistico: si vorrebbe offrire
agli studenti, ovvero agli studiosi che muovono i primi passi
all'interno della disciplina, uno stumento agile alla rapida
consultazione, che contenga i una prima scelta dei lemmi più comuni in
cui è possibile imbattersi, e per cui occorre una definizione chiara e
lineare, senza eccessivi rimandi o appesantimenti.

\[*Antonello~Fabio~Caterino*\]

[^1]: GLODIUM -- Glossario di informatica umanistica. Progetto ideato e
    diretto da Antonello Fabio Caterino, a cura di Marcello Bolpagni,
    Antonello Fabio Caterino e Marco Petolicchio. ISBN 9788832173086. Al
    momento, il progetto è ospitato all'interno del *carnet de
    recherche* *Filologia Risorse Informatiche*,
    <https://fri.hypotheses.org>.

[^2]: Si rimanda al sito
    <https://eadh.org/projects/glodium-glossario-di-informatica-umanistica>.



# Esiste un'umanistica non digitale? {-}

\markboth{Esiste un'umanistica non digitale?}{Marco Petolicchio}


Appare a molti, e in maniera trasparente, quanto l'utilizzo degli strumenti informatici stia contribuendo ad un ripensamento sostanziale delle forme tipiche del lavoro umanistico. Lo testimonia il crescente numero di convegni, riviste, progetti internazionali, studi interdisciplinari, corsi di laurea, vòlti a domandarsi il senso e la funzione di questa figura emergente all'interno degli studi umanistici in senso lato: quella dell'umanista digitale.
Appare nondimeno evidente il ruolo cardinale dei mezzi informatici nella designazione degli spazi tipici d'interesse e di lavoro di uno studioso di materie umanistiche. Una scomposizione operata nella frammentazione di un *continuo* quale l'oggetto-libro, da atomo inscindibile nelle sue parti costituenti alla piena dissezione, quasi uno smantellamento minuzioso della topografia di quelle che erano le forme tipiche di fruizione della conoscenza.
Così, nozioni che fino a qualche decennio fa potevano apparire come un campo esclusivo delle \`\`scienze dure\" rientrano oggi nello spazio esplorabile dalla curiosità dell'umanista, laddove la ricerca del *dato* diviene una misura analitica della quantità di *informazione* di un elemento di studio, aprendo la via ad un'investigazione ad ampio spettro del testo letterario, non più univocamente legato al proprio contenuto referenziale bensì interfaccia esso stesso di una complessa relazione di elementi interni ed esterni, che configura una rete di conoscenza complessa, dalla geometria sfuggevole e seducente^[Sull'idea di \`\`granularità\" e \`\`frammentazione\" si può fare riferimento al recente Roncaglia, G., *L'età della frammentazione. Cultura del libro e scuola digitale*, Roma-Bari, Laterza, 2018].
Slegata l'informazione dal suo *integumentum* essa può essere manipolata, analizzata, comparata nelle sue più piccole componenti in un continuo gioco di scomposizione, tale da rendere possibile la formazione di nuove e fino ad ora impensabili analogie tra i dati, che si offrono allo studioso in una dimensione agnostica, nuda, pronta ad accogliere le sue curiosità.

Si potrebbe dire che in un certo senso gli strumenti informatici possano contribuire a rompere quel tacito patto tra l'autore e il lettore, legati in quello spazio fisico dell'indivisibilità dei contenuti, e permettere in maniera sin troppo semplice di operare quasi chirurgicamente una tale estrapolazione di informazioni così da poterne evidenziare aspetti ora slegati dall'impresa narrativa, come nel caso delle opportunità offerte dagli approcci orientati al *distant reading*^[Si possono consigliare, a tale scopo, i lavori di Franco Moretti ed, in particolare: Moretti, F., *Graphs, maps, trees: abstract models for a literary history*, Londra-New York: Verso, 2005 e Moretti, F., *Distant Reading*, Londra: Verso, 2013.], 
oppure indagare, con un viatico di segni e simboli, le tracce stilistiche dell'autore ora nascosto dal lavoro letterario, avvalendosi dell'uso di indagini quantitative, verso una filologia attributiva assistita dagli strumenti digitali.    
Così un umanista digitale potrà estrarre un certo numero di informazioni che potranno essere poi processate, visualizzate, comparate, trasformate, passando da una realtà concreta quale, in ultima analisi, la sbavatura dell'inchiostro su una pagina del libro, ad una rappresentazione astratta e mediata dal computer di quegli stessi elementi informativi, in un incessante scambio di informazioni tra l'oggetto fisico e la sua rappresentazione digitale^[Si pensi anche al lavoro di Padre Roberto Busa, sostanziale precorritore di tali applicazioni, che dall'inizio degli anni '50 del secolo scorso ebbe l'intuizione di utilizzare i primi calcolatori a schede perforate per allestire una lemmatizzazione integrale delle opere di Tommaso d'Aquino.]. 

Ma non solamente il modo di approcciare un testo ha conosciuto questo epocale cambio di paradigma. Non solo dunque gli strumenti, quanto l'oggetto stesso dell'indagine di studio conosce uno slittamento orizzontale delle sue definizioni. Cosa distingue e definisce un *testo* come una tipologia di informazione studiabile, riconoscibile rispetto ad altri, altrettanto possibili? Notevole è il numero di studi che iniziano ad interfacciare prodotti del mondo digitale quale strumento nativo di ricerca: così emergono le analisi linguistiche dei *post* sui social network, si aprono le analogie tra reti sociali digitali e analogiche, si comparano i comportamenti sulle piattaforme virtuali con quelli dell'esperienza quotidiana. In tale maniera possiamo pensare a queste tecnologie non come un mero strumento utile per applicazioni con finalità statistiche e quantitative, quanto ad una integrale opera di allargamento dell'universo del conoscibile in tutte le sue forme costituenti, come spazio complanare di interessi a quelli ben sperimentati^[Owens, T., *Defining Data for Humanists: Text, Artifact, Information or Evidence?*, in *Journal of Digital Humanities*, Num.1 Vol.1, 2011, <http://journalofdigitalhumanities.org/1-1/defining-data-for-humanists-by-trevor-owens/>]: in qualche modo, sebbene con qualche esitazione, potremmo definire che almento in parte vi è in atto un certo slittamento nel passaggio da uno studio centrato cardinalmente intorno al *monumento* letterario al *documento*.

La domanda iniziale, che dà il titolo a questo mio breve contributo, vorrebbe dunque focalizzarsi su un punto che potrebbe essere centrale in questa analisi: attraverso quali modalità possiamo ripensare una disciplina, quale quella degli studi umanistici, che sia al contempo basata su mezzi informatici, computazionali o digitali?
Se da un lato questo sviluppo in senso tecnico --sia pure tecnicistico-- degli studi umanistici pare inarrestabile, essa comporta nondimeno una riflessione ad ampio spettro sulle modalità in cui questa si manifesta e sugli sviluppi che con essa scaturiscono per l'intera società.

Se vi è una forma di *utilità* sociale che potrebbe essere indirizzata agli studi umanistici probabilmente è quella della testimonianza delle forme di conoscenza attuale verso la posterità, quel \`\`ponte\" culturale che permetta una continuità di sapere tra ieri e domani, contingentato in uno spazio presente sfaccettato e multiforme. 
In questo ponte di conoscenze in senso verticale, l'umanista potrebbe essere simbolo di un Caronte di saperi, il cui compito primario è proprio quello di \`\`traghettare\" tali conoscenze da un punto all'altra della storia. Così egli ha ora la possibilità di riflettere su quali possano essere le tecnologie più sicure per un simile viaggio, tali da assicurare il più possibile l'accesso alla posterità e in questo senso indagare, di volta in volta, gli strumenti più adatti allo scopo, sconfinando egli stesso in aree remote di conoscenze. Lo potremo vedere p.es. mentre si applica alla trascrizione di un documento attraverso l'uso di un linguaggio di *markup*, oppure perdersi in *fogli di calcolo* dall'aspetto francamente infernale, estrapolare i dati attraverso brevi *script* scritti in un *linguaggio di programmazione ad alto livello*, per poi trasformare questa informazione in forma di grafici, mappe, vettori, giochi di luce, suoni e così via, in una continua opera di *astrazione* e rimodellamento dell'informazione^[Per un ben più esaustivo contributo alla discussione cfr. Ciotti, F., *Digital Heritage/Digital Humanities: una linea di faglia?*, 2016, <https://infouma.hypotheses.org/295>.]. 

Questo tempo presente ci appare in grande fermento tecnologico. Un fermento foriero di nuovi stimoli che permette all'umanista di travalicare non solo i recinti tipici della propria materia di studio ma che in qualche modo ne incoraggia lo sconfinamento verso altre forme del sapere, in un approccio altamente interdisciplinare tale che, per necessità di espansione stessa dell'oggetto e dei metodi di indagine, fomenta per sua stessa natura la formazione di \`\`reti\" di conoscenze in senso collaborativo, laddove il lavoro strettamente individuale non riuscirebbe ad accogliere una così grande molteplicità di vedute tale da convogliarle in una singola persona. Così all'umanista non è richiesta solamente una certa responsabilità in senso \`\`diacronico\" --il trasporto delle conoscenze verso la posterità-- quanto una riflessione \`\`sincronica\" sullo stato di cose presenti nel suo agire concreto e contingente nel tempo attuale. Tale offerta che ci si pone innanzi implica una costante responsabilizzazione delle modalità dell'agire nelle proprie scelte di ricerca e nei metodi con cui essa va verificandosi.

Questa alfabetizzazione informatica, necessaria laddove gli strumenti di natura computazionale *latu sensu* hanno assunto il ruolo primario di mezzo privilegiato attraverso cui si opera il lavoro di studio, non può limitarsi dunque ad un mero uso passivo dei mezzi digitali, quanto è auspicabile una presa di coscienza di quelle forme di libertà che scaturiscono dalla scelta di un tipo di tecnologia piuttosto che un'altra. Sebbene fenomeni quali il *digital divide* --la divisione cioè tra una parte di popolazione che ha accesso alla rete rispetto a chi non la possiede-- appare assottigliarsi^[Lohr, S., *Digital Divide Is Wider Than We Think, Study Says*, in *The New York Times*, 04/12/2018, <https://www.nytimes.com/2018/12/04/technology/digital-divide-us-fcc-microsoft.html>], esso non rappresenta che *una* delle criticità insite nel problema dell'accesso alla conoscenza nel mondo digitale, che riguardano le forme di licenze attraverso cui si distribuiscono e riutilizzano le ricerche^[Haspelmath, M., *Why open-access publication should be nonprofit: a view from the field of theoretical language science*, in *Frontiers in Behavioral Neuroscience*, 7, 2013, <https://doi.org/10.3389/fnbeh.2013.00057>], la punibilità legale in caso di violazione delle leggi sul copyright^[Tra i casi più eclatanti in tale senso preme ricordare almeno quello del giovane Aaron Swartz, reo di aver scaricato illegalmente un consistente numero di articoli scientifici dal repository a pagamento \textsc{jstor}, per cui venne condannato a 35 anni di reclusione, morendo suicida a New York nel 2013.] e l'utilizzo di piattaforme più o meno libere per lo scambio delle ricerche^[Una risposta in tale senso è stata fornita dall'elaborazione di licenze meno restrittive in termini di riutilizzo dei prodotto, che designano l'universo dell'*open knowledge* (*open source* e *open access* tra gli altri).] tra le tante problematiche in tal senso.

Districarsi all'interno di questo variegato mondo di conoscenze appare uno sforzo notevole per lo studioso di discipline umanistiche (umanista *digitale*, *informatico* o *umanista 2.0* che dir si voglia), ma offre al contempo la possibilità di ridefinizione di uno spazio di lavoro e ricerca di una figura che per necessità opera attivamente nel dialogo e nella collaborazione interdisciplinare con altri saperi che si trovano a cooperare all'interno di uno spazio digitale sempre più pervasivo nella vita di ognuno di noi.




\[*Marco~Petolicchio*\]